### ISSUE TITLE
Reactivity Transform

### ISSUE THREAD

**Issue by phantomlsh** [sxzz/vue-macros#416]
### Describe the bug

When running `npm run dev`, the following error pops out:

```
> v3-web@0.0.0 dev
> vite

failed to load config from W:\xxxx\vite.config.js
error when starting dev server:
TypeError: Cannot set property resolveObjectKey of #<Object> which has only a getter
    at Object.<anonymous> (W:\xxxx\node_modules\@vue-macros\common\dist\index.js:298:1574)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at _require.extensions.<computed> [as .js] (file:///W:/xxxx/node_modules/vite/dist/node/chunks/dep-8609dc5d.js:66118:17)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (W:\xxxx\node_modules\@vue-macros\reactivity-transform\dist\chunk-TUFSP3Z4.js:170:15)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
```

I am confused since the reactivity transform works perfectly in version 0.3.7, but the failure appears in version 0.3.12.

### Reproduction

import { defineConfig } from 'vite' import vue from '@vitejs/plugin-vue' import reactivityTransform from '@vue-macros/reactivity-transform/vite'  // https://vitejs.dev/config/ export default defineConfig({   base: './',   plugins: [vue(), reactivityTransform()] })

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Memory: 8.15 GB / 15.92 GB
  Binaries:
    Node: 18.12.1 - T:\Nodejs\node.EXE
    npm: 8.18.0 - T:\Nodejs\npm.CMD
  Browsers:
    Chrome: 114.0.5735.199
    Edge: Spartan (44.22621.1848.0), Chromium (114.0.1823.58)
    Internet Explorer: 11.0.22621.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
Please upgrade to the latest version `unplugin-vue-macros@2.3.4`

**Comment by guohuihot** [comment]
webpack@5.82.0也报错儿，不知道是不是这个问题
